### ISSUE TITLE
Include project details in the academic staff profile pages 

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#106]
> Prof. Roshan Ragel
```
Could we also include the list of projects under the staff profile pages as well? 
I believe it is there for the student profiles and not in staff?
...
I also realize the list for the staff one could go very long. 
Therefore, I am happy to hear any alternative solution you would have.
```

For the,
- Course projects, we can allow having links to the course page, if the staff member was supervised that course project.
- FYP research projects, I think we can directly add project cards to the supervisor's profile page.

We need to address the quantity issue in a sustainable and automated way. (I think we don't need to fill the staff profile page with 100+ projects in the next 5 years.) 

I will try to assign this task to the team who work on the 6SP project, *"Research Profiles for Academic Staff"*

**Comment by gihanjayatilaka** [comment]
If we are adding publications to the staff pages at some point, we can include the project page as a link under the publication citation.
eg:
Author 1, Author 2, and Author 3. Paper title. Conference name (2022). [PDF, arXiv, DOI, **Project Page**]

This way, we will show project pages only for a limited number of projects.
