### ISSUE TITLE
iframe integration for staff members 

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#107]
We need to provide an iFrame option for staff members who haven't GitHub accounts, to fill the content in the staff profile pages

- iframe height should be automatically adjusted into the content height (no iframe scrollbars)
- Add an optional field to the staff page YML

**Comment by NuwanJ** [comment]
@ishanfdo18098 If you have free time, can you check this and implement the iFrame integration for Dr. Janaka? (Maybe we can integrate it into the same staff layout, as an optional feature. 

PS:
- Use CE Projects shared drive for Google doc creation

**Comment by ishanfdo18098** [comment]
Just to check if I understood properly, What I should do is create an iframe in the staffDetails layout to show the google doc ?

**Comment by NuwanJ** [comment]
Yes, if *iframe* was provided, skip rendering the *{{ content }}* and show the iframe window (The challenging task is how to adjust the height of the iFrame according to the content size)

**Comment by ishanfdo18098** [comment]
Let's just change the method,

- Have the .html files in google drive (Then anyone can edit the files with permission)
- Download the files from the drive using a python script every day using github actions

I think this method is easier to implement 😁

**Comment by NuwanJ** [comment]
Yes, that is also nice idea. Lets try that. 

Can we edit the files with .html extension didirectly from GDrive ?

(Another possibility is to export the G Doc as html and fetch.)

**Comment by ishanfdo18098** [comment]
> Can we edit the files with .html extension directly from GDrive ?

![image](https://user-images.githubusercontent.com/73381996/169637146-4d01e334-23d4-4c2e-9ce0-2af4d6ef538e.png)



> (Another possibility is to export the G Doc as html and fetch.)

Then we'll have to add the jekyll frontmatter manually. I think its better to have that file as .html in drive and just download it.

**Comment by ishanfdo18098** [comment]
Please delete these two files from gDrive as they are no longer needed 
![image](https://user-images.githubusercontent.com/73381996/169638092-53b48a46-3408-43ba-8cff-4f9f833440c1.png)

https://drive.google.com/drive/folders/11HiLuEnDxPTQN2wCqTRKWpQrH7URS_oa
