### ISSUE TITLE
Update the color scheme similar to the Faculty colors 

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#112]

**Comment by ishanfdo18098** [comment]
What is the color scheme ? 😇

**Comment by NuwanJ** [comment]
It is pink

**Comment by ishanfdo18098** [comment]
> It is pink

![image](https://user-images.githubusercontent.com/73381996/172099602-09f8ec6a-ddf2-4e28-bc17-9ebd0559f231.png)

🤣

**Comment by NuwanJ** [comment]
That seems not to do 😧
