### ISSUE TITLE
ACES past committee member details

### ISSUE THREAD

**Issue by ishanfdo18098** [cepdnaclk/people.ce.pdn.ac.lk#115]
Add all the requirements here

**Comment by NuwanJ** [comment]
An email sent to ACES president, and will wait for their response

**Comment by NuwanJ** [comment]
#105 will work on the this

**Comment by NuwanJ** [comment]
We received the information from 2015 onwards; 
https://drive.google.com/file/d/1-RBeTZ4mRtm_ccc6TSzRFLwMDSoUXYdh/view?usp=sharing
