### ISSUE TITLE
Gathering more data from Alumni

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/people.ce.pdn.ac.lk#117]
We can gather the information from https://www.facebook.com/acespera/posts/4761622913947824 to fill our JSONs. This can be done using a simple script.

**Comment by NuwanJ** [comment]
I have access to the information (Google Sheet). Will wait some time until most of the alumni fill it.

**Comment by NuwanJ** [comment]
We haven't enough useful data in that Google Form (we haven't consent to publish the emails)
