### ISSUE TITLE
Postgraduate Student Details

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#138]
From Dr. Upul Jayasinghe

Please add [this form](https://forms.gle/mpo2jarU7b9eWz9F7) to https://www.ce.pdn.ac.lk/people/Postgrdauate Students (need to create this path/ not in https://people.ce.pdn.ac.lk/). The idea is to share this form with all prospective and current Ph.D./Mphil students and get their details (as we don't have such a system yet). 

Please make sure to display only the following information in the public profile. 

- Name with Initials
- Registration Number
- Email
- Degree
- Mode of Study
- Research Topic
- Profile Picture
- Website

**Comment by NuwanJ** [comment]
This is the Google Sheet that contains the information:

https://docs.google.com/spreadsheets/d/e/2PACX-1vR6ntuDUUuzQS84Am7NMcCc6LCTYKmUfMbVhp4dvy1AXWoVxNrjWfeQntWg5cAfLsFvb4WASQRp-erT/pub?output=csv

**Comment by NuwanJ** [comment]
@ishanfdo18098 Are you free for this? Will be an half hour of work for you I think

**Comment by ishanfdo18098** [comment]
> @ishanfdo18098 Are you free for this? Will be an half hour of work for you I think

Yeah. I will take a look at this 😇

**Comment by NuwanJ** [comment]
Nice, and thanks very much.

1. I will add you into the email thread with Dr. Upul.
2. For now, we don't need individual pages for them. We can do what we done for the temporary Instructors. (This is a suggested way in my head: https://nuwanj.github.io/people.ce.pdn.ac.lk/staff/temporary-academic-staff/)
3. Lets put following info for now:
  - Name with Initials
  - Registration Number
  - Email
  - Degree
  - Mode of Study
  - Research Topic
  - Profile Picture
  - Website (will pre-process and put icons too)

5. Note that Postgrad students can edit the form responses at anytime

**Comment by ishanfdo18098** [comment]
> For now, we don't need individual pages for them. 

I'm already in the process of making individual pages

**Comment by NuwanJ** [comment]
That is fine. What you hope to use for the index? As we informed so far, all postgrad students haven't registration number

**Comment by NuwanJ** [comment]
TODO list:

- [ ] Add a link to the Google Form at the bottom of the postgrad page 
- [ ] Use reversed list (New students will appear first)
- [ ] Hide the reg number, if it is selected as "Provisional" 
- [ ] Group the students by the type of the degree (PhD, MPhil, MEng, MSc, Provisional)
- [ ]
