### ISSUE TITLE
staffDetails breadcrumb wrong on lecturers

### ISSUE THREAD

**Issue by ishanfdo18098** [cepdnaclk/people.ce.pdn.ac.lk#148]
![image](https://user-images.githubusercontent.com/73381996/172588495-94e42545-aabc-4986-b87a-356868a50a47.png)
![image](https://user-images.githubusercontent.com/73381996/172588513-8c14323a-aa62-4b88-8d6f-2e2f3bdbcd2e.png)
![image](https://user-images.githubusercontent.com/73381996/172588519-ec705ca3-2ab2-4abf-9bb6-4cd32ed6ff50.png)

It should be "lecturer" instead of "senior lecturer"

**Comment by ishanfdo18098** [comment]
Everything looks okay to me, but it doesn't work 😥


https://github.com/cepdnaclk/people.ce.pdn.ac.lk/blob/10ec0c18665d46910989dfc02ef4705760787f51/_layouts/staffDetails.html#L51-L57
https://github.com/cepdnaclk/people.ce.pdn.ac.lk/blob/10ec0c18665d46910989dfc02ef4705760787f51/pages/staff/academic-staff/amila-indika.html#L19-L23

**Comment by ishanfdo18098** [comment]
We have used the same wrong else if in some other places too, should we change them ?
![image](https://user-images.githubusercontent.com/73381996/172596101-508c53a1-3097-45a5-a8b1-16164c3e4ac3.png)

**Comment by NuwanJ** [comment]
Ya, let's fix and test the site

**Comment by ishanfdo18098** [comment]
> Ya, let's fix and test the site

done
