### ISSUE TITLE
Change the title Academic Support Staff

### ISSUE THREAD

**Issue by damayanthiHerath** [cepdnaclk/people.ce.pdn.ac.lk#168]
The current group of employees listed under Academic Support Staff are under Non-Academic staff category in the university system. 
The title should be changed to Non-Academic Staff. Please change the link text in the peoples home and any other to make it consistent through out the site.

**Comment by NuwanJ** [comment]
Done with commit [7d61124](https://github.com/cepdnaclk/people.ce.pdn.ac.lk/commit/7d611243565c455fb7fcf726ca4ab36a40e8a106)
