### ISSUE TITLE
Finding the latest update for a record

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/people.ce.pdn.ac.lk#175]
Hi!
Say t1<t2<t3 are timestamps.
t1: Google form submission.
t2: Git commit.
t3: Google form submission.

How can we make sure that our github action does not pull information from t1 during time t when t2<t<t3?

**Comment by NuwanJ** [comment]
Good point. We can use the timestamp details in the Google Form submission and consider only the same day (or better, we can use a 3-day period, in case GH Actions were not worked on a day or 2) records to overwrite the files in the GitHub repository. 

@ishanfdo18098 what do you think about this?

**Comment by ishanfdo18098** [comment]
I have updated the python script to compare the last modified time of the file using git with the timestamp in the google form responses.

**Comment by ishanfdo18098** [comment]
That didn't work. Have to try again

**Comment by ishanfdo18098** [comment]
![image](https://user-images.githubusercontent.com/73381996/196760408-6b12ddae-e764-43dc-979b-91b2471605aa.png)

GitHub actions last file edited time is always the github action execution time. Need to find another method to find the last file edited time

**Comment by NuwanJ** [comment]
Hi @ishanfdo18098,

I think we don't need to check the last updated date of the files inside the repo. We can compare the timestamp in the Google Form response to see if there are any new updates.

One other way is that we can keep a separate file that will check the last updated date. I have implemented a similar feature for the undergraduate courses [here](https://github.com/cepdnaclk/undergraduate-courses/blob/22cd3b4904bcdec0308c84e64fcaf01260aa583e/python_scripts/aggregate_course.py#L58).

**Comment by ishanfdo18098** [comment]
Now working properly
![image](https://user-images.githubusercontent.com/73381996/199772785-a499b3ef-1939-4409-9791-391f84c2392d.png)


The problem was in 
https://github.com/cepdnaclk/people.ce.pdn.ac.lk/blob/50e0e2d4c60b1a64412dd2da9ae8c18f7280ce23/.github/workflows/daily.yml#L15-L20

By default the clone depth is set to 1. So only the latest commit is cloned. Fixed it by cloning with all past commits in the gh action
