### ISSUE TITLE
Update in E/19 students list

### ISSUE THREAD

**Issue by damayanthiHerath** [cepdnaclk/people.ce.pdn.ac.lk#177]
There is an update in our E19CO list. We need to replace Mr. R.P.S. Ranasinghe (E/19/314) with Mr. R.B. Abeysinghe (E/19/004).

**Comment by ishanfdo18098** [comment]
E/19/314 Removed
![image](https://user-images.githubusercontent.com/73381996/190572649-139d7e80-32d0-4305-a25b-538e50cb698a.png)

E/19/004 Added
![image](https://user-images.githubusercontent.com/73381996/190572689-a19a3a8d-86ef-40d1-9cdc-4a7fc1dd57ba.png)
![image](https://user-images.githubusercontent.com/73381996/190572714-3f0ccdc4-9036-4041-811b-6012127fc2f8.png)
