### ISSUE TITLE
Name missing in search

### ISSUE THREAD

**Issue by ridmajayasundara** [cepdnaclk/people.ce.pdn.ac.lk#185]
<img width="628" alt="Screenshot 2022-10-06 at 9 15 45 AM" src="https://user-images.githubusercontent.com/73826052/194209617-3842ad92-38b4-4717-b75b-3a13d3ffd0f3.png">

**Comment by NuwanJ** [comment]
Seems we need to check the availability of the name fields when generating the search.json
