### ISSUE TITLE
Fill details/content to pages

### ISSUE THREAD

**Issue by ishanfdo18098** [cepdnaclk/people.ce.pdn.ac.lk#27]
- [x] Fill remaining Academic Staff pages
    - [x] Prof. Roshan G. Ragel 
    - [x] Dr. Asitha Bandaranayake 
    - [x] Dr. Damayanthi Herath 
    - [x] Dr. Dhammika Elkaduwe
    - [x] Dr. Eng. Kamalanath Samarakoon
    - [x] Dr. Isuru Nawinne
    - [x] Dr. Janaka Alawatugoda
    - [x] Dr. Mahanama Wickramasinghe
    - [x] Dr. Manjula Sandirigama
    - [x] Dr. Shirley Devapriya Dewasurendra
    - [x] Dr. Sithumini Ekanayake
    - [x] Dr. Suneth Namal Karunarathna
    - [x] Dr. Swarnalatha Radhakrishnan
    - [x] Dr. Upul Jayasinghe
    - [x] Mr. D. S. Deegalla
    - [x] Mr. Ziyan Maraikar
- [x] Fill Past Heads of the Department
- [x] Fill Temporary Academic Staff
     - [x] Link to profile page 
- [x] Fill Academic Support Staff

**Comment by NuwanJ** [comment]
Suggestion: 
- Add a YML parameter into the "Fill Temporary Academic Staff", that can direct to the student profile page (Most of the instructors will have their own student profile page)
- On the web page, you can put a tiny button or anchor to that page

**Comment by NuwanJ** [comment]
I go through all Staff pages and all seems to be ok now. Good Job!
