### ISSUE TITLE
Visiting Lecturers and Visiting Research Fellows

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#291]
Prof. Roshan:

`Please add two more links here and a separate group: Visiting Lecturers and Visiting Research Fellows - let's have it between the first three and the last two`

![image](https://user-images.githubusercontent.com/11540782/198186029-a1a26a8c-8772-4e2f-a38e-30fd6818224f.png)

**Comment by NuwanJ** [comment]
The URLs can be 
- https://people.ce.pdn.ac.lk/staff/visiting-lecturers/
- https://people.ce.pdn.ac.lk/staff/visiting-research-fellows/

The page layout may be similar to the instructions. Details that need to be collected/shown are, 
- `Name`
- `Email`
- `Position` (Ex: Prof. at UNSW, Australia)
- `Profile Image`
- `Profile Link (optional)`
- `Linkedin Profile (optional)`

**Comment by ishanfdo18098** [comment]
Notes:

- Name cards for now. Separate pages later if requested

**Comment by ishanfdo18098** [comment]
TODOs:


- [ ] Add them into the search

**Comment by ishanfdo18098** [comment]
@NuwanJ  Do we need a google form to collect data ?

**Comment by NuwanJ** [comment]
@ishanfdo18098 Let's start with the JSON file option (like for Instructors)

**Comment by damayanthiHerath** [comment]
We have a new list. How to add them?

**Comment by NuwanJ** [comment]
@damayanthiHerath madam, we implemented, but have not deployed the updates since we had not any of them yet. If you have a list, could you able to share it with me/us? Later we will add the documentation on the `way on how to add new entries`. 

We need,
- Name 
- Email (Organizational Email is preferred)
- Current Permanent Position and the Organization
- Is a Visiting Lecturer or Visiting Research Fellow

Optional Details: 
- A profile link/links (Institutional profile page / ResearchGate profile / Google Scholar profile)
- Linkedin Profile Link

**Comment by damayanthiHerath** [comment]
The relavent details are[ here](https://docs.google.com/spreadsheets/d/1QLrRP3k-tQYUe12gZ2gZma22RFuI4v99XuaU_ly830A/edit?usp=sharing), please do the needful

**Comment by NuwanJ** [comment]
TODO

- [ ] Implement a model view to show the full details (which are not shown on the People Cards)
- [ ] Double-check the links of each research fellow
- [ ] Integrate with search results and in People API

**Comment by ishanfdo18098** [comment]
@NuwanJ do we need a profile page for each person ?

**Comment by NuwanJ** [comment]
@ishanfdo18098 

All of them are 'Visiting' staff and they already have profiles in their permanent workplace, I think we don't need to maintain a separate page for them. And giving a unique page address will be quite challenging.

But we have some details, not possible to show on the Profile Card itself (remarks and designations). Shall we try to implement a Modal Popup and show the details when someone clicked on the card? (Similar thing we already using for Performance Badges on student pages)

**Comment by damayanthiHerath** [comment]
Thank you. Two minor suggestions for changes:
The title should be Honorary Visiting Research Fellows
The name Dr. Hasindu Gamarachchi should be Dr. Hasindu Gamaarachchi
