### ISSUE TITLE
Avoid overwriting the profile page HTML contents by Google Form data fetch script

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#301]
Students can add custom HTML text into their profiles by entering those after the `frontmatter`. But currently, the Google Form python script (python_scripts/update_profile_from_google_form.py) will overwrite them with Google Form content update.

https://github.com/cepdnaclk/people.ce.pdn.ac.lk/blob/f40d04e86072580fb4458617c75b4f2324bcf06d/python_scripts/update_profile_from_google_form.py#L99

It is possible to avoid that in the pyton script by following above `TODO` item.

**Comment by ishanfdo18098** [comment]
I will do this on the 11th of February 😄

**Comment by ishanfdo18098** [comment]
Tested it and confirmed that it works.

https://github.com/cepdnaclk/people.ce.pdn.ac.lk/actions/runs/4150046557/jobs/7179428363
![image](https://user-images.githubusercontent.com/73381996/218243390-5ba896a8-037b-43cf-98a0-7f2ee1ba489c.png)

40f9aa0e1f36bb83aa2cbb9e7b2124a3e40d09eb

**Comment by ishanfdo18098** [comment]
Looks like there's a sliiiiight problem with the script

https://github.com/cepdnaclk/people.ce.pdn.ac.lk/blob/main/pages/students/e04/e04145.html
https://github.com/cepdnaclk/people.ce.pdn.ac.lk/blob/main/pages/students/e99/e99047.html

looks like my custom HTML was written to these profiles

**Comment by ishanfdo18098** [comment]
This was caused because,
`
 existingContentAfterFrontMatter = ""
`
only executed if the file existed. As these profile were new ones (Added only 20hrs ago). The line didnt execute and it had the value from the last iteration of the loop which was an testing entry from me. 

Moving that line out of the 
`if exists(file_url):` 
should fix the problem
