### ISSUE TITLE
[Error] Update profiles with Google Form 

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#303]
Daily build action is failing with the following error. Could you able to check it?

```
-------------
Processing: E/04/145 Amaradasage Kasun Buddika Karunathilake
Downloading image to images/students/e04/e04145.jpg
Error: Process completed with exit code 1.
```

**Comment by ishanfdo18098** [comment]
The e04 image folder was missing. I created the folder. Looks like it works now

**Comment by NuwanJ** [comment]
Update the download script a little. Can you check if I break something?

**Comment by ishanfdo18098** [comment]
added comment at d1ff4d37a4568d0ba55e6aa054bf3cda20959b3f

**Comment by NuwanJ** [comment]
I also added "" for the location, since we can't guarantee text inputs in Google Form

```md
location: \"{location}\"
```
