### ISSUE TITLE
Research publication listing

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/people.ce.pdn.ac.lk#306]
Hi,
We need to start showing the publication's author list with links to the author profiles (eg: https://cepdnaclk.github.io/publications/). This is important because the audience can "follow a line of work/group". Also, hope this can increase the number of times students reach out to authors for collaborations / extending other's work.

**Comment by gihanjayatilaka** [comment]
Great!

**Comment by NuwanJ** [comment]
![image](https://user-images.githubusercontent.com/11540782/225402140-b99e05a1-a199-440f-bf51-f12675084d32.png)
