### ISSUE TITLE
Getting rid of wordpress pages for academic staff profiles

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/people.ce.pdn.ac.lk#318]
1.  Write a forwarding script from https://www.ce.pdn.ac.lk/academic-staff/XXX to https://people.ce.pdn.ac.lk/staff/academic/XXX
2.  Delete https://www.ce.pdn.ac.lk/academic-staff/XXX

**Comment by NuwanJ** [comment]
1. We can use a WordPress redirection plugin
2. Let's write redirection for it too (as well as for other staff pages there)

@damayanthiHerath madam, how we can proceed on this?

**Comment by gihanjayatilaka** [comment]
Some problems take care of themselves 😁
