### ISSUE TITLE
"Edit this page on GitHub" button

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#32]
@gihanjayatilaka  suggested adding an "Edit this page on GitHub" button into the profile pages. Then students can easily find the file and edit it.

A similar implementation you can find on the following page:
- https://pera-swarm.ce.pdn.ac.lk/docs/robot/virtual-robot/setup-guide

Source: https://github.com/Pera-Swarm/docs

**Comment by ishanfdo18098** [comment]
Moved to the footer

![image](https://user-images.githubusercontent.com/73381996/145075737-ae0266e6-b241-4b5e-a85f-0253c888a01c.png)

**Comment by NuwanJ** [comment]
This is fine
