### ISSUE TITLE
Adding E96, E97

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/people.ce.pdn.ac.lk#347]
E96 and E97 are missing in our database.

**Comment by gihanjayatilaka** [comment]
https://docs.google.com/spreadsheets/d/1Gi2BqcFI2KKED6ZRaI69TLbNHzNzMobf788VRTJUkIo/edit#gid=10973310

**Comment by ishanfdo18098** [comment]
Should I add details from this sheet to the site ? 
What columns shoud I add ?

**Comment by gihanjayatilaka** [comment]
ENo, name, email address and country
