### ISSUE TITLE
Link the Publication information with PG student profiles 

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#352]
- [x] Use `_data/student_publications.json` as the data source (The dictionary Key will be the email). For now, no data. I'll tag the PG students and update the Publication API ASAP. c53c884141045a14c57997d8eee32a487ea75868

- [x] Additionally, please append the PG Student list into `api/students.json` too. Use `MSc` / 'PhD' / 'MPhil' as the `"batch"` and keep the fields we haven't any data as blank. 3839507df8a6d90ddc409c4df69d634c261cec26

We need to get this done before the IESL visit of the department in the coming week.

**Comment by NuwanJ** [comment]
@ishanfdo18098 can't we use the email as the id / key of the dictionary? Not every PG student have reg number, and we are currently tagging their publications with the email address.

**Comment by ishanfdo18098** [comment]
Done

**Comment by NuwanJ** [comment]
Can you remove the mock publication data and merge the PR ?
