### ISSUE TITLE
Add E/20 Cohort 

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#356]
@ishanfdo18098 can you work on this? 

I am attaching the list of E/20 CO and E/19 Mechatronics students (they both follow second-year common courses together and therefore, let's have them under the E/20 people's page for now). 
-Prof. Roshan

Please work on the issue branch. I will take a look at what we can do for E19 ME students and E18 ME student.  

- [E20CO.xlsx](https://github.com/cepdnaclk/people.ce.pdn.ac.lk/files/13302742/E20CO.xlsx)
- [CO222_2023 Mechatronics Students.xlsx](https://github.com/cepdnaclk/people.ce.pdn.ac.lk/files/13302740/CO222_2023.Mechatronics.Students.xlsx)

**Comment by IshanFernandoClouda** [comment]
Where can I find the profile pictures ?

**Comment by NuwanJ** [comment]
Last time you got those from FEeLS as I remember. Can we do it this time too? 
(Will it be possible with the new FEeLS ?)

**Comment by IshanFernandoClouda** [comment]
I tried downloading from FEeLS for E19 batch at that time. It looked like I couldn't view E19 students profiles using my account (In new FEeLS). Then Dr. Damayanthi sent me photos of the whole batch that was used for the Student ID card. Have to try again for E20. I will try and let you know

**Comment by NuwanJ** [comment]
In this case, let's use the default profile picture (https://people.ce.pdn.ac.lk/images/students/default.jpg) for all the students. I will ask Chandula and team to encourage students to submit their profile picture at the Orientation program.

**Comment by IshanFernandoClouda** [comment]
I checked just now. Looks like we can view the profiles now. But there are no profile images yet.
![image](https://github.com/cepdnaclk/people.ce.pdn.ac.lk/assets/140997769/51c31d19-147d-4753-9972-d8d597007cdc)

https://feels.pdn.ac.lk/user/profile.php?id=2881 (You can increase 2881 and view other profiles)

**Comment by IshanFernandoClouda** [comment]
> In this case, let's use the default profile picture (https://people.ce.pdn.ac.lk/images/students/default.jpg) for all the students. I will ask Chandula and team to encourage students to submit their profile picture at the Orientation program.

Okay :)

**Comment by ishanfdo18098** [comment]
Theres a small problem. E19 mech students will show up on E19 page. Not in E20 page

**Comment by NuwanJ** [comment]
Lets keep them on their for now. I will discuss about it with HoD. Can you push the changes and make a PR ? (Hope you worked on a seperate branch.)

**Comment by IshanFernandoClouda** [comment]
#357

**Comment by NuwanJ** [comment]
@ishanfdo18098 I got the profile images, so I updated to the images/students/e20. Can you update the student profiles with the image paths ?

**Comment by ishanfdo18098** [comment]
Added

**Comment by ishanfdo18098** [comment]
> Theres a small problem. E19 mech students will show up on E19 page. Not in E20 page

I can fix this by using something like `batch_to_appear_on: E20" in the frontmatter if we need to show the E19 students in E20 page

**Comment by NuwanJ** [comment]
> > Theres a small problem. E19 mech students will show up on E19 page. Not in E20 page
> 
> I can fix this by using something like `batch_to_appear_on: E20" in the frontmatter if we need to show the E19 students in E20 page

If we go with this, we have to make some considerations for the API portal, and the mapping logic will be too complex. Additionally, Google Form submissions also affect with this. So I got permission to keep them on the E19 page.

**Comment by IshanFernandoClouda** [comment]
> > > Theres a small problem. E19 mech students will show up on E19 page. Not in E20 page
> > 
> > 
> > I can fix this by using something like `batch_to_appear_on: E20" in the frontmatter if we need to show the E19 students in E20 page
> 
> If we go with this, we have to make some considerations for the API portal, and the mapping logic will be too complex. Additionally, Google Form submissions also affect with this. So I got permission to keep them on the E19 page.

Thanks for pointing that out. I didn't think about the API and google form side of things
