### ISSUE TITLE
Updating the Badges of the students

### ISSUE THREAD

**Issue by chandula00** [cepdnaclk/people.ce.pdn.ac.lk#381]
- [x] Badges of Casual Instructors - [find details here](https://docs.google.com/spreadsheets/d/1aGjwO46ZI9y46fk9IRhNgE-sIUOAFfznWXen2yE5Bmg/edit?usp=sharing)
- [x] Web Consultation Team - [find details here](https://webteam.gs.pdn.ac.lk/)
- [x] In addition to that, have to update details about recent and ongoing ACES committees. [details](https://docs.google.com/spreadsheets/d/1OA2EFqPxd1tralznFYydS8kah4Rk1aGqGU0ycaDbQp8/edit?usp=sharing).

**Comment by ishanfdo18098** [comment]
Some clarifications are needed, 

1) What are the semester numbers for the given periods in the casual instructor google sheet ?
a) Oct-2023 to Nov-2023
b) Jan-2024 to Feb-2024
c) Oct-2023 to Feb-2024

The semester number is needed to fill the .json at 
https://github.com/cepdnaclk/people.ce.pdn.ac.lk/blob/8ebf93468e0c0978b904a5ce881b92abfa7c3f38/_data/badges.json#L53

2) What is the year for the ACES committee? 2024 right ? Looks like we have missing data for 2023 ?  https://people.ce.pdn.ac.lk/societies/

**Comment by chandula00** [comment]
1. All those are coming into Semester 3 and 5
2. As far as I know, the term of the previous committee was from February 2023 to January 2024 (also, as indicated in all the documents and posters it is committee 23/24). The current committee’s term began in February 2024 and may conclude within this year.

**Comment by ishanfdo18098** [comment]
Is it possible to get a registration number list for the Web Consultation Team ?
(Just the registration number is enough)

**Comment by chandula00** [comment]
[Here I made a gsheet](https://docs.google.com/spreadsheets/d/12vT5n0SggR1PHlv-AAzVHN6BGymHyuzT-u5VyKuPHEw/edit?usp=sharing)

**Comment by ishanfdo18098** [comment]
> [Here I made a gsheet](https://docs.google.com/spreadsheets/d/12vT5n0SggR1PHlv-AAzVHN6BGymHyuzT-u5VyKuPHEw/edit?usp=sharing)

Thank you


Couple of things that I noticed.

E/18/147 has the course code as COCO327 
![image](https://github.com/cepdnaclk/people.ce.pdn.ac.lk/assets/73381996/f1010c5b-9a16-426f-a9b0-b25cc20a6677)

ACES 2024 google sheet has Saadias reg number as E/19. Shes from E18
![image](https://github.com/cepdnaclk/people.ce.pdn.ac.lk/assets/73381996/08f0fc17-d54e-4bfd-b534-85db9cfdd4f1)

You may want to fix the files that you took the information from.

**Comment by chandula00** [comment]
Thanks, I fixed those
I think now we can close the issue, right?
