### ISSUE TITLE
A few GUI improvement suggestions

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#44]
The followings are a few suggestions to improve the GUI

- Move the *Documentation* from the NavBar to Footer 
- Remove *Search* page link from the NavBar and add a search box into the homepage (Once the search button is clicked, it will navigate to the search page with the keyword; can use GET to pass the keyword)

**Comment by ishanfdo18098** [comment]
- Documentation moved to footer
![image](https://user-images.githubusercontent.com/73381996/145719760-27f67058-4cea-4e9f-a52a-c2807358ff3e.png)
![image](https://user-images.githubusercontent.com/73381996/145719777-8dbe66db-115c-4ea7-b93d-aec4d614bcb4.png)


- Search moved to homepage
![image](https://user-images.githubusercontent.com/73381996/145719796-35cb046c-60d1-4aa8-809c-580c747f40a1.png)
- Searching for something will remove the cards and show the output
![image](https://user-images.githubusercontent.com/73381996/145719828-1f0ab40d-c5c2-429d-8e32-2c4f7fef26d3.png)

**Comment by NuwanJ** [comment]
Nice! 😎

Another suggestion: Can we make the homepage like the following? It will balance the home page 

![image](https://user-images.githubusercontent.com/11540782/145827598-1aae4eb8-9d44-4a5d-a5f8-7c91c9f2a77c.png)

**Comment by NuwanJ** [comment]
@ishanfdo18098  @Piumal1999 

Suggestion: Is it possible to avoid hiding the content on the home page, when we are using the search option?

**Comment by ishanfdo18098** [comment]
Yes, its possible. I will look into it.
