### ISSUE TITLE
Breadcrumb not working on batches E15 and E16

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#46]
![image](https://user-images.githubusercontent.com/11540782/146008190-11d872d8-935a-4ce0-9f6d-bda84b9e5d38.png)

**Comment by ishanfdo18098** [comment]
The problem was in the permalink. 
Changed 
`permalink: "/students/e14/390"`
to
`permalink: "/students/e14/390/"`
in every file
