### ISSUE TITLE
Add interests

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#47]
This is a suggestion to add a new property/field to allow students to add their fields of interest. 

Ex: IoT, Machine Learning, Embedded Systems, etc...

**Comment by ishanfdo18098** [comment]
Fixed in 5348407c2925039ebd36891fdde1ffe8e3bd4772

- [ ] Add that into studentDetails layout

**Comment by ishanfdo18098** [comment]
Done. 
Works in cepdnaclk/api.ce.pdn.ac.lk@db89f1a14fca2af9c732471be0e7c2007b02d3e6 too
