### ISSUE TITLE
Privacy Issue: Emails

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#48]
There is a privacy issue of showing the emails (especially the private email) on the profile page. 
We will discuss and find a solution and update here. 

- Add an option to decide whether it should be visible on the web
- Format the email in a way username [at] domain.com format in the web

Feel free to comment your suggestions also @ishanfdo18098 @Piumal1999

**Comment by ishanfdo18098** [comment]
Are we trying to stop spam from bots ?

**Comment by Piumal1999** [comment]
> * Add an option to decide whether it should be visible on the web
This option seems better. 

Btw, won't there be a privacy issue when we keep emails in GitHub repo files?

**Comment by NuwanJ** [comment]
Closed with 6c4e5e937a18fa0266031a7d1970edf957081709
