### ISSUE TITLE
Advance Search

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#53]
There is a suggestion to develop an advance search for the people site

**Comment by ishanfdo18098** [comment]
What needs to be there in the advanced search ?
Things like search by batch, search by location ?

**Comment by NuwanJ** [comment]
Need to check for user scenarios and decide. We can do this in that phase 2, after the major requirements are finished.

**Comment by ishanfdo18098** [comment]
Add a button for advanced search
- Write in a docs page that advanced search can be done using the existing search
- Or create a new advanced search consisting of different things to search by

**Comment by NuwanJ** [comment]
Dr. Damayanthi suggested adding the contents of the Staff into the advance search (Area of Expertise)

**Comment by ishanfdo18098** [comment]
Added in #94
