### ISSUE TITLE
Add a few new Fields to the students

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#54]
Followings are the new fields requested to add for the student pages (frontmatter):

- Current Affiliation (Default: Faculty of Engineering, University of Peradeniya, for the Alumni, the company they work)
- Department: Computer/Mechanical
- Graduation Year or Date: Empty for current students
- Bio (Similar to the staff pages, in the content, by default, it will be empty. We can provide examples in the documentation)

(Better if we discussed those changes in the next meeting, before implement)

**Comment by NuwanJ** [comment]
As get confirmed, 
- We need to tag students by the department (CO/ME) 
- Add ME, students, as a separate section of the batch

**Comment by NuwanJ** [comment]
Added the following 2 parameters into the student pages. Will send a PR soon

- department
- current_affiliation

**Comment by ishanfdo18098** [comment]
TODO:
- [ ] Update the documentation 
- [ ] Update the frontend 
    - current_affiliation > optional field in the student profile pages
    - Need to group the students as Computer and Mechatronic in the batch lists
- [ ] Update the API

**Comment by ishanfdo18098** [comment]
> Need to group the students as Computer and Mechatronic in the batch lists

should this be done similar to how academic staff is grouped in https://cepdnaclk.github.io/people.ce.pdn.ac.lk/staff/academic/ using tabs ?

something like this, 
![image](https://user-images.githubusercontent.com/73381996/147377286-ad73fefc-df90-4516-abd7-7f0925e12584.png)

**Comment by NuwanJ** [comment]
What about a design like this?
(Dr. Isuru said that Production students also will join for a few courses in the future)

![image](https://user-images.githubusercontent.com/11540782/147817256-80ab69a2-5cfb-4ce7-810b-360e6689b83a.png)

**Comment by ishanfdo18098** [comment]
> What about a design like this? 

Thats better. Easier to implement too 😄

**Comment by NuwanJ** [comment]
Accepted
