### ISSUE TITLE
Scholar/DBLP/Semantic Scholar URLs

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/people.ce.pdn.ac.lk#66]
We might need to get the URL for publication trackers for both students and staff. We might be able to use them to scrape people's pubs to create the publication repository of the department.

Almost everyone has a google scholar and we can collect that as the minimum. However, dblp and semanticscholar might be easier for API access compared to google scholar.

**Comment by NuwanJ** [comment]
We can fetch the DBLP information using the Search API with using just the name in most cases. Will look about this deeply in the **"publications"** project
