### ISSUE TITLE
Misssing link in documentation

### ISSUE THREAD

**Issue by ishanfdo18098** [cepdnaclk/people.ce.pdn.ac.lk#84]
There is no link to https://people.ce.pdn.ac.lk/documentation/run-locally/ from the [documentation ](https://people.ce.pdn.ac.lk/documentation/) index page. 

Should we add it back ?

@NuwanJ

**Comment by NuwanJ** [comment]
Yes, please add it.

I'm thinking about adding another page like "Maintainer Guide" by explaining the functionality of GitHub Actions, python scripts etc...
