### ISSUE TITLE
Write documentation page "Maintainers Guide"

### ISSUE THREAD

**Issue by ishanfdo18098** [cepdnaclk/people.ce.pdn.ac.lk#89]
Include documentation for,

- [x] GitHub Action
- [x] Python Scripts
- [x] Maintainer Responsibilities (https://docs.google.com/document/d/1vb9eTqLTf9tnCAtkQLbwsyixf76XjxqG4dza8b1AsY8/edit?usp=sharing)

Please fill in the other topics that are needed

**Comment by NuwanJ** [comment]
@ishanfdo18098 can you update the Google Doc with GitHub Action and Python Script information will be useful for a new maintainer?

https://docs.google.com/document/d/1vb9eTqLTf9tnCAtkQLbwsyixf76XjxqG4dza8b1AsY8/edit?usp=sharing

PS:
- I added you as the current maintainer 😃

**Comment by ishanfdo18098** [comment]
Updated! Please check



> PS:
I added you as the current maintainer 😃

༼ つ ◕_◕ ༽つ

**Comment by NuwanJ** [comment]
@ishanfdo18098 

- [ ] Adding Staff Google Drive sync option procedures to the documentation

**Comment by ishanfdo18098** [comment]
Updated :smile:
