### ISSUE TITLE
Student and Alumni Forms issue

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#98]
https://github.com/cepdnaclk/people.ce.pdn.ac.lk/blob/8cf880888f6176f409302bb4e12e2e72d9b53097/_includes/footer.html#L55-L65

I'm thinking about having a single *Form* is better, since a student can be alumni in a later year, and manually updating that condition for each year/batch is not sustainable.

Prepared one with conditional pages (not finalized yet)
- https://forms.gle/XkArBdMtBVE5MqeNA

Can you comment on your opinions here?
@gihanjayatilaka @Akilax0 @ishanfdo18098 @Piumal1999

**Comment by ishanfdo18098** [comment]
The new form is also okay. 

But, can't we just use one of the existing forms ? The only difference between Alumni and Student form is the current affiliation part and the rest is similar. There's no difference in the python scripts too.

My idea is, Rename the alumni form as student and use only that to collect data.

**Comment by ishanfdo18098** [comment]
Added new google form to site.

2a83d4d28144bfb1ec4b34244bd6b4e5f05dc635
774337a825c88ad4b5893ae06b960d758f53baff
ca1e709ca59ad5280d4f1e3c45d7fe96031e4f7e
fdffb412970f49466fe35af08955f268d7ef9fe7
